version: "3"
services: 
    requests_to_slack:
        image: requests_to_slack
        container_name: requests_to_slack
        build: ./requests_to_slack
        volumes: 
            - ./requests_to_slack:/work
        networks: 
            - learn-linux-scraping_net
        tty: true
    splash:
        image: scrapinghub/splash
        container_name: splash
        networks: 
            - learn-linux-scraping_net
networks: 
    learn-linux-scraping_net:
        driver: bridge